name: Setup
description: Action that sets up Node, pnpm, and caching

runs:
  using: composite
  steps:
    - name: Setup pnpm
      uses: pnpm/action-setup@v4

    - name: Install bun
      uses: oven-sh/setup-bun@v2

    - name: Setup Node.js environment
      uses: actions/setup-node@v6
      with:
        node-version: 20.x
        # cache: "pnpm"
        package-manager-cache: false
        registry-url: 'https://registry.npmjs.org'

    #    - name: Install safe chain
    #      shell: bash
    #      run: |
    #        npm i -g @aikidosec/safe-chain
    #        safe-chain setup-ci

    - name: Setup Git User
      shell: bash
      run: |
        git config --global user.email "stijn@stijnvanhulle.be"
        git config --global user.name "Stijn Van Hulle"

    - name: Get pnpm store directory
      shell: bash
      id: pnpm-cache
      run: |
        echo "pnpm_cache_dir=$(pnpm store path)" >> $GITHUB_OUTPUT

    - uses: actions/cache@v4
      name: Setup pnpm cache
      with:
        path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-

    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile

    - name: Setup Turbo cache
      uses: rharkor/caching-for-turbo@v2.3.5
      continue-on-error: true
      with:
        # Set the prefix for the cache keys.
        cache-prefix: kubb_

    # - name: Get base and head commits for `nx affected`
    #   uses: nrwl/nx-set-shas@v4.1.2
    #   with:
    #     main-branch-name: main
